sudo: false
language: node_js
node_js: 10
branches:
  only:
    - master
notifications:
  email: true
script:
  - npm run validate
after_success:
  - npm run report-coverage
  - npm run semantic-release